### ISSUE TITLE
[Question] Maximum number of temp variables

### ISSUE THREAD

**Issue by emanuelev** [fbenz/FpDebug#9]
Hi there,

Apologies if this is not the right place to ask a "support" question. 

I am hoping to use FpDebug to track down a pretty nasty bug plaguing a system I am working on (3D vision specifically) which I think might be caused by floating point precision. I managed to build FpDebug and launch the application with valgrind, however I hit straight away the assert ` tl_assert(tmp >= 0 && tmp < MAX_TEMPS);`. Am I right to think that is some limit on the application size that FpDebug might work with? Notice that my app is fairly large (roughly 60k lines of code).

Many thanks!
Emanuele

**Comment by fbenz** [comment]
Hi Emanuele,

The upper limit of 1000 is arbitrary and I never changed it, because it was sufficient for my tests. Just change it to a higher number and compile it again.
```
#define	MAX_TEMPS							1000
```

Best regards,
Florian

**Comment by emanuelev** [comment]
Hi Florian,

Thank you very much for this. I've set it to a much bigger number and now it seems to be working. I'll let you know if I face any other problem.

Best wishes,
Emanuele
